Feature/match result
WildCodeSchool/wild-fighting pull request #12
Opened 2019-10-24 09:29 UTC by jn-html

La features s’appelle match-result car de base je devais faire les 2 composent "Winner" et "Loser", mais en cours de sprint mon équipier à récupérer le composant "Loser" donc la feature "match-result" est donc la features "WInner"

2019-10-25 07:35 UTC, Aebrathia requested changes

2019-10-25 07:35 UTC, Aebrathia commented on src/components/WinnerPage/Winner.css
> + }
Global styles and html selectors should be put inside index.css and not in components

2019-10-25 07:35 UTC, Aebrathia commented on src/components/WinnerPage/Winner.css
> +.winnerResult{
Unconsistent naming convention on classes. Choose one convention and everyone in your team should use the same.

2019-10-25 07:35 UTC, Aebrathia commented on src/components/WinnerPage/Winner.css
> +.roll-in-blurred-left {
Unconsistent naming convention on classes. Choose one convention and everyone in your team should use the same.

2019-10-25 07:35 UTC, Aebrathia commented on src/components/WinnerPage/Winner.css
> +.v_1 {
Unconsistent naming convention on classes. Choose one convention and everyone in your team should use the same.

2019-10-25 07:35 UTC, Aebrathia commented on src/components/WinnerPage/Winner.css
> +fin du code du menu*/
Remove comments before commiting

2019-10-25 07:35 UTC, Aebrathia commented on src/components/WinnerPage/Winner.css
> +button {
Don't use html selectors in the component's css file.

2019-10-25 07:35 UTC, Aebrathia commented on src/components/WinnerPage/Winner.css
> +button {
Otherwise you risk impacting other components in your page. This way components wouldn't be independant.

2019-10-25 07:35 UTC, Aebrathia commented on src/components/WinnerPage/Winner.css
> +   }
You don't need to write vendor prefixes like `-webkit-` because `create-react-app` uses a tool that add them automatically.

2019-10-25 07:35 UTC, Aebrathia commented on src/components/WinnerPage/Winner.js
> +                                {/*<button>Share it</button> */}
Remove comments from code before commiting.

2019-10-25 07:35 UTC, Aebrathia commented on src/components/WinnerPage/Winner.js
> +                    <div className='slide-in-blurred-top'><div className = "winResultTitle"><h1>VICTORY</h1></div></div>
Don't write text in uppercase, write it normally and use the css property `text-transform: uppercase;`

2019-10-25 07:35 UTC, Aebrathia commented on src/components/WinnerPage/Winner.js
> +    </button>*/}</div>
Same as before

2019-10-31 10:26 UTC, Aebrathia requested changes
Avoid using files with spaces in their name like `Pokemon Solid.ttf`. Rename the file instead.

2019-10-31 10:26 UTC, Aebrathia commented on package.json
> +    "react-font-face": "^0.2.1",
You don't need a package to write a few lines of css to add a `@font-face`

2019-10-31 10:26 UTC, Aebrathia commented on src/components/WinnerPage/Winner.css
> +.win-result-title > h1 {
Prefer using one single class instead of using an html selector.

2019-10-31 10:26 UTC, Aebrathia commented on src/components/WinnerPage/Winner.js
> +                    <div className='slide-in-blurred-top'><div className = "win-result-title"><h1 style={{fontFamily:"pokemon_hollow"}}>victory</h1></div></div>
Use css to add font-family, not inline styles.

2019-10-31 10:26 UTC, Aebrathia commented on src/components/WinnerPage/Winner.js
> +        </div>
Indent correctly and remove empty brackets.

2019-10-31 10:26 UTC, Aebrathia commented on src/components/WinnerPage/Winner.js
> +export default Winner;
Add missing newline at the end of the file

2019-11-04 14:23 UTC, RemyPottierFr commented
@Aebrathia

2019-11-13 14:05 UTC, closed without merging